### ISSUE TITLE
Build error on iPhone <6

### ISSUE THREAD

**Issue by mugx** [KosyanMedia/Hotellook-iOS-SDK-Core#1]
I am getting build error trying to build with iPhone 4s/5
<img width="252" alt="screen shot 2017-07-18 at 08 01 04" src="https://user-images.githubusercontent.com/7835402/28293494-5ee4ca54-6b8f-11e7-96d8-c44a9a3f9a94.png">
are you experiencing the same problem?

note:
on iPhone >=6 is building fine

**Comment by sevabill** [comment]
Hi, we've added support for i386, please check out the latest release: https://github.com/KosyanMedia/Hotellook-iOS-SDK-Core/releases/tag/v1.0.1
