### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Nalorokk** [KosyanMedia/Hotellook-iOS-SDK-Core#3]
Module compiled with Swift 4.0.2 cannot be imported in Swift 3.3: project/Pods/HotellookSDK/Library/HotellookSDK.framework/Modules/HotellookSDK.swiftmodule/x86_64.swiftmodule

**Comment by MontakOleg** [comment]
Hi @Nalorokk

SDK supports only last version of swift. If you want to use swift 3, you can download  [old version](https://github.com/KosyanMedia/Hotellook-iOS-SDK-Core/releases/tag/v1.0.1) of SDK

But it's better to use last xCode & Swift version in your project.

**Comment by Nalorokk** [comment]
@MontakOleg this problem appeared after recent (March 30) update of Xcode to version 9.3

**Comment by MontakOleg** [comment]
@Nalorokk, I will check

**Comment by MontakOleg** [comment]
@Nalorokk please check version 1.0.5:
```
pod 'HotellookSDK', :git => 'https://github.com/KosyanMedia/Hotellook-iOS-SDK-Core.git', :tag => 'v1.0.5'
```
